/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import javax.swing.JDialog;

/**
 *
 * @author Manuel Aguilar Herrera
 */
public class jfprincipal extends javax.swing.JFrame {
    /**
     * Creates new form jfprincipal
     */
    public jfprincipal() {
        initComponents();
    }
    static int valor_globl = 0;
    static boolean valida = false;
    static String mensaje_salida = "";
    
    
    public void validar(int valor, int seleccion) {
        mensaje_salida="";
        valida = false;
        int r = 0;
        if (seleccion == 0) {
            if (valor == 1000) {
                mensaje_salida = "producto entregado";
                System.out.println("producto entregado");
                jlproducto.setSelectedIndex(-1);
                valida = true;
            } else if (valor < 1000) {
                r=1000-valor;
                mensaje_salida = "faltan "+r +" pesos";
                System.out.println("falta dinero");
            } else {
                r = valor - 1000;
                mensaje_salida = "le sobraron: " + r+" pesos";
                valor_globl = 0;
                System.out.println("le sobraron: " + r+" pesos");
            }
        }
        if (seleccion == 1) {
            if (valor == 1500) {
                mensaje_salida = "producto entregado";
                System.out.println("producto entregado");
                jlproducto.setSelectedIndex(-1);
                valida = true;
            } else if (valor < 1500) {
                 r=1500-valor;
                mensaje_salida = "faltan "+r +" pesos";
                System.out.println("falta dinero");
            } else {
                r = valor - 1500;
                mensaje_salida = "le sobraron: " + r+" pesos";
                valor_globl = 0;
                System.out.println("le sobraron: " + r +" pesos");
            }
        }
        if (seleccion == 2) {
            if (valor == 2000) {
                mensaje_salida = "producto entregado";
                System.out.println("producto entregado");
                jlproducto.setSelectedIndex(-1);
                valida = true;
            } else if (valor < 2000) {
                 r=2000-valor;
                mensaje_salida = "faltan "+r +" pesos";
                System.out.println("falta dinero");
            } else {
                r = valor - 2000;
                mensaje_salida = "le sobraron: " + r +" pesos";
                valor_globl = 0;
                System.out.println("le sobraron: " + r);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlproducto = new javax.swing.JList();
        jB500 = new javax.swing.JButton();
        jB200 = new javax.swing.JButton();
        jB100 = new javax.swing.JButton();
        jB1000 = new javax.swing.JButton();
        jBFin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbxValorIngresado = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbxMensaje = new javax.swing.JTextPane();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Seleccione la opcion:");

        jlproducto.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "1) Refrescos en envase plástico ($1000)", "2) Bebida energizante ($1500)", "3) Refresco en lata ($2000)" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jlproducto.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jlproductoValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jlproducto);

        jB500.setText("$500");
        jB500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB500ActionPerformed(evt);
            }
        });

        jB200.setText("$200");
        jB200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB200ActionPerformed(evt);
            }
        });

        jB100.setText("$100");
        jB100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB100ActionPerformed(evt);
            }
        });

        jB1000.setText("$1000");
        jB1000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB1000ActionPerformed(evt);
            }
        });

        jBFin.setText("fin");
        jBFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFinActionPerformed(evt);
            }
        });

        jLabel2.setText("Valor ingresado:");

        tbxValorIngresado.setEnabled(false);
        jScrollPane2.setViewportView(tbxValorIngresado);

        jLabel3.setText("Mensaje de salida:");

        tbxMensaje.setEnabled(false);
        jScrollPane3.setViewportView(tbxMensaje);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jB100)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jB200)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jB500)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jB1000)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBFin, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane3))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jB500, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(jB200, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jB100, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jB1000, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlproductoValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jlproductoValueChanged
        if (jlproducto.getSelectedIndex() == 0) {
            System.out.println("selecciono uno");

        } else if (jlproducto.getSelectedIndex() == 1) {
            System.out.println("selecciono 2");
        } else {
            System.out.println("selecciono 3");
        }
    }//GEN-LAST:event_jlproductoValueChanged

    private void jB100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB100ActionPerformed
       mensaje_salida="";
        valor_globl = valor_globl + 100;
        tbxValorIngresado.setText(String.valueOf(valor_globl));
        tbxMensaje.setText(mensaje_salida);
        System.out.println("valor= " + valor_globl);
        
    }//GEN-LAST:event_jB100ActionPerformed

    private void jB200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB200ActionPerformed
        mensaje_salida="";
        valor_globl = valor_globl + 200;
        tbxValorIngresado.setText(String.valueOf(valor_globl));
        tbxMensaje.setText(mensaje_salida);
        System.out.println("valor= " + valor_globl);
    }//GEN-LAST:event_jB200ActionPerformed

    private void jB500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB500ActionPerformed
        mensaje_salida="";
        valor_globl = valor_globl + 500;
        tbxValorIngresado.setText(String.valueOf(valor_globl));
        tbxMensaje.setText(mensaje_salida);
        System.out.println("valor= " + valor_globl);
    }//GEN-LAST:event_jB500ActionPerformed

    private void jB1000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB1000ActionPerformed
        mensaje_salida="";
        valor_globl = valor_globl + 1000;
        tbxValorIngresado.setText(String.valueOf(valor_globl));
        tbxMensaje.setText(mensaje_salida);
        System.out.println("valor= " + valor_globl);
    }//GEN-LAST:event_jB1000ActionPerformed

    private void jBFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFinActionPerformed
        System.out.println("seleccion>>>" + jlproducto.getSelectedIndex());
        if (jlproducto.getSelectedIndex() == -1) {
            mensaje_salida = "Debe seleccionar algún producto";
            tbxMensaje.setText("Debe seleccionar algún producto");
            System.out.println("Debe seleccionar algún producto");
        } else {
            validar(valor_globl, jlproducto.getSelectedIndex());
            tbxValorIngresado.setText(String.valueOf(valor_globl));
        }
        if (valida) {
            valor_globl = 0;
        }
        tbxMensaje.setText(mensaje_salida);
    }//GEN-LAST:event_jBFinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jB100;
    private javax.swing.JButton jB1000;
    private javax.swing.JButton jB200;
    private javax.swing.JButton jB500;
    private javax.swing.JButton jBFin;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList jlproducto;
    private javax.swing.JTextPane tbxMensaje;
    private javax.swing.JTextPane tbxValorIngresado;
    // End of variables declaration//GEN-END:variables
}
